export {Home} from "./Home/Home"
export {Books} from "./Books/Books.jsx"
export {AddBooks} from "./Books/AddBooks"
export {Community} from "./Community/Community"
export {Profile} from "./Profile/Profile"
export {Login} from "./Profile/Login"
export {Register} from "./Profile/Register"
export {Favs} from "./Favs/Favs"
export {MyPosts} from "./Profile/MyPosts"

export {Trivia} from "./Trivia/Trivia"
